# Generated by Django 5.2.4 on 2025-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_plate', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('year_make', models.IntegerField()),
                ('hiring_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
