# Generated by Django 5.2.4 on 2025-08-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_car_num_plate_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookiing_date',
            new_name='booking_date',
        ),
    ]
